//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsFiler.Presentation.Resources;

using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("PublicResXFileCodeGenerator", "")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Strings
{
    private static ResourceManager resourceMan;

    private static CultureInfo resourceCulture;

    public Strings()
    {
    }

    public static ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                resourceMan = new ResourceManager("WsFiler.Presentation.Resources.Strings", typeof(Strings).Assembly);
            }

            return resourceMan;
        }
    }

    public static CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string App_Title => ResourceManager.GetString("App.Title", resourceCulture)!;

    public static string Menu_AboutWsFiler => ResourceManager.GetString("Menu.AboutWsFiler", resourceCulture)!;

    public static string About_Title => ResourceManager.GetString("About.Title", resourceCulture)!;

    public static string About_Description => ResourceManager.GetString("About.Description", resourceCulture)!;

    public static string Status_Ready => ResourceManager.GetString("Status.Ready", resourceCulture)!;

    public static string Status_PreviewUnavailable => ResourceManager.GetString("Status.PreviewUnavailable", resourceCulture)!;

    public static string Status_NoItemToCopy => ResourceManager.GetString("Status.NoItemToCopy", resourceCulture)!;

    public static string Status_NoItemToMove => ResourceManager.GetString("Status.NoItemToMove", resourceCulture)!;

    public static string Status_NoItemToDelete => ResourceManager.GetString("Status.NoItemToDelete", resourceCulture)!;

    public static string Status_NoItemToRename => ResourceManager.GetString("Status.NoItemToRename", resourceCulture)!;

    public static string Status_Copied => ResourceManager.GetString("Status.Copied", resourceCulture)!;

    public static string Status_Moved => ResourceManager.GetString("Status.Moved", resourceCulture)!;

    public static string Status_Deleted => ResourceManager.GetString("Status.Deleted", resourceCulture)!;

    public static string Status_Renamed => ResourceManager.GetString("Status.Renamed", resourceCulture)!;

    public static string Status_AlreadyAtRoot => ResourceManager.GetString("Status.AlreadyAtRoot", resourceCulture)!;

    public static string Status_OperationCanceled => ResourceManager.GetString("Status.OperationCanceled", resourceCulture)!;

    public static string Dialog_Copy_Title => ResourceManager.GetString("Dialog.Copy.Title", resourceCulture)!;

    public static string Dialog_Copy_MessageSingle => ResourceManager.GetString("Dialog.Copy.MessageSingle", resourceCulture)!;

    public static string Dialog_Copy_MessageMultiple => ResourceManager.GetString("Dialog.Copy.MessageMultiple", resourceCulture)!;

    public static string Dialog_Copy_Destination => ResourceManager.GetString("Dialog.Copy.Destination", resourceCulture)!;

    public static string Dialog_Move_Title => ResourceManager.GetString("Dialog.Move.Title", resourceCulture)!;

    public static string Dialog_Move_MessageSingle => ResourceManager.GetString("Dialog.Move.MessageSingle", resourceCulture)!;

    public static string Dialog_Move_MessageMultiple => ResourceManager.GetString("Dialog.Move.MessageMultiple", resourceCulture)!;

    public static string Dialog_Move_Destination => ResourceManager.GetString("Dialog.Move.Destination", resourceCulture)!;

    public static string Dialog_Rename_Title => ResourceManager.GetString("Dialog.Rename.Title", resourceCulture)!;

    public static string Dialog_Rename_NewName => ResourceManager.GetString("Dialog.Rename.NewName", resourceCulture)!;

    public static string Dialog_Duplicate_Title => ResourceManager.GetString("Dialog.Duplicate.Title", resourceCulture)!;

    public static string Dialog_Duplicate_NewName => ResourceManager.GetString("Dialog.Duplicate.NewName", resourceCulture)!;

    public static string Dialog_Common_Ok => ResourceManager.GetString("Dialog.Common.Ok", resourceCulture)!;

    public static string Dialog_Common_Yes => ResourceManager.GetString("Dialog.Common.Yes", resourceCulture)!;

    public static string Dialog_Common_No => ResourceManager.GetString("Dialog.Common.No", resourceCulture)!;

    public static string Dialog_Common_Cancel => ResourceManager.GetString("Dialog.Common.Cancel", resourceCulture)!;

    public static string Dialog_Common_Close => ResourceManager.GetString("Dialog.Common.Close", resourceCulture)!;

    public static string Dialog_Preview_Title => ResourceManager.GetString("Dialog.Preview.Title", resourceCulture)!;

    public static string Dialog_Preview_Truncated => ResourceManager.GetString("Dialog.Preview.Truncated", resourceCulture)!;

    public static string Grid_Column_Name => ResourceManager.GetString("Grid.Column.Name", resourceCulture)!;

    public static string Grid_Column_Ext => ResourceManager.GetString("Grid.Column.Ext", resourceCulture)!;

    public static string Grid_Column_Size => ResourceManager.GetString("Grid.Column.Size", resourceCulture)!;

    public static string Grid_Column_Modified => ResourceManager.GetString("Grid.Column.Modified", resourceCulture)!;

    public static string Pane_Summary => ResourceManager.GetString("Pane.Summary", resourceCulture)!;

    public static string Status_SortChanged => ResourceManager.GetString("Status.SortChanged", resourceCulture)!;

    public static string Status_DirectoryCreated => ResourceManager.GetString("Status.DirectoryCreated", resourceCulture)!;

    public static string Status_FileCreated => ResourceManager.GetString("Status.FileCreated", resourceCulture)!;

    public static string Status_Duplicated => ResourceManager.GetString("Status.Duplicated", resourceCulture)!;

    public static string Status_AttributesChanged => ResourceManager.GetString("Status.AttributesChanged", resourceCulture)!;

    public static string Dialog_Drive_Title => ResourceManager.GetString("Dialog.Drive.Title", resourceCulture)!;

    public static string Dialog_Attributes_Title => ResourceManager.GetString("Dialog.Attributes.Title", resourceCulture)!;

    public static string Dialog_Attributes_ReadOnly => ResourceManager.GetString("Dialog.Attributes.ReadOnly", resourceCulture)!;

    public static string Dialog_Attributes_Hidden => ResourceManager.GetString("Dialog.Attributes.Hidden", resourceCulture)!;

    public static string Dialog_Attributes_Archive => ResourceManager.GetString("Dialog.Attributes.Archive", resourceCulture)!;

    public static string Dialog_Attributes_System => ResourceManager.GetString("Dialog.Attributes.System", resourceCulture)!;

    public static string Dialog_UnixAttributes_Title => ResourceManager.GetString("Dialog.UnixAttributes.Title", resourceCulture)!;

    public static string Dialog_UnixAttributes_Owner => ResourceManager.GetString("Dialog.UnixAttributes.Owner", resourceCulture)!;

    public static string Dialog_UnixAttributes_Group => ResourceManager.GetString("Dialog.UnixAttributes.Group", resourceCulture)!;

    public static string Dialog_UnixAttributes_Other => ResourceManager.GetString("Dialog.UnixAttributes.Other", resourceCulture)!;

    public static string Dialog_UnixAttributes_Read => ResourceManager.GetString("Dialog.UnixAttributes.Read", resourceCulture)!;

    public static string Dialog_UnixAttributes_Write => ResourceManager.GetString("Dialog.UnixAttributes.Write", resourceCulture)!;

    public static string Dialog_UnixAttributes_Execute => ResourceManager.GetString("Dialog.UnixAttributes.Execute", resourceCulture)!;

    public static string Dialog_UnixAttributes_SetUserId => ResourceManager.GetString("Dialog.UnixAttributes.SetUserId", resourceCulture)!;

    public static string Dialog_UnixAttributes_SetGroupId => ResourceManager.GetString("Dialog.UnixAttributes.SetGroupId", resourceCulture)!;

    public static string Dialog_UnixAttributes_StickyBit => ResourceManager.GetString("Dialog.UnixAttributes.StickyBit", resourceCulture)!;

    public static string Dialog_UnixAttributes_ReadOnlyMessage => ResourceManager.GetString("Dialog.UnixAttributes.ReadOnlyMessage", resourceCulture)!;

    public static string Dialog_DirectoryCreate_Title => ResourceManager.GetString("Dialog.DirectoryCreate.Title", resourceCulture)!;

    public static string Dialog_DirectoryCreate_Prompt => ResourceManager.GetString("Dialog.DirectoryCreate.Prompt", resourceCulture)!;

    public static string Dialog_FileCreate_Title => ResourceManager.GetString("Dialog.FileCreate.Title", resourceCulture)!;

    public static string Dialog_FileCreate_Prompt => ResourceManager.GetString("Dialog.FileCreate.Prompt", resourceCulture)!;

    public static string Dialog_Filter_Title => ResourceManager.GetString("Dialog.Filter.Title", resourceCulture)!;

    public static string Dialog_Filter_Prompt => ResourceManager.GetString("Dialog.Filter.Prompt", resourceCulture)!;

    public static string Dialog_Filter_ShowHidden => ResourceManager.GetString("Dialog.Filter.ShowHidden", resourceCulture)!;

    public static string Dialog_Editor_Title => ResourceManager.GetString("Dialog.Editor.Title", resourceCulture)!;

    public static string Dialog_Editor_Prompt => ResourceManager.GetString("Dialog.Editor.Prompt", resourceCulture)!;

    public static string Status_SearchNotFound => ResourceManager.GetString("Status.SearchNotFound", resourceCulture)!;

    public static string Status_PathCopied => ResourceManager.GetString("Status.PathCopied", resourceCulture)!;

    public static string Status_BookmarkAdded => ResourceManager.GetString("Status.BookmarkAdded", resourceCulture)!;

    public static string Status_CompareRequiresFiles => ResourceManager.GetString("Status.CompareRequiresFiles", resourceCulture)!;

    public static string Status_CompareSame => ResourceManager.GetString("Status.CompareSame", resourceCulture)!;

    public static string Status_CompareDifferent => ResourceManager.GetString("Status.CompareDifferent", resourceCulture)!;

    public static string Dialog_Search_Title => ResourceManager.GetString("Dialog.Search.Title", resourceCulture)!;

    public static string Dialog_Search_Prompt => ResourceManager.GetString("Dialog.Search.Prompt", resourceCulture)!;

    public static string Dialog_Bookmark_Title => ResourceManager.GetString("Dialog.Bookmark.Title", resourceCulture)!;

    public static string Dialog_Bookmark_Prompt => ResourceManager.GetString("Dialog.Bookmark.Prompt", resourceCulture)!;

    public static string Dialog_History_Title => ResourceManager.GetString("Dialog.History.Title", resourceCulture)!;

    public static string Dialog_History_Prompt => ResourceManager.GetString("Dialog.History.Prompt", resourceCulture)!;

    public static string Dialog_FileSearch_Title => ResourceManager.GetString("Dialog.FileSearch.Title", resourceCulture)!;

    public static string Dialog_FileSearch_FileName => ResourceManager.GetString("Dialog.FileSearch.FileName", resourceCulture)!;

    public static string Dialog_FileSearch_BaseDirectory => ResourceManager.GetString("Dialog.FileSearch.BaseDirectory", resourceCulture)!;

    public static string Dialog_FileSearch_SearchDirectories => ResourceManager.GetString("Dialog.FileSearch.SearchDirectories", resourceCulture)!;

    public static string Dialog_FileSearch_Start => ResourceManager.GetString("Dialog.FileSearch.Start", resourceCulture)!;

    public static string Dialog_FileSearch_Jump => ResourceManager.GetString("Dialog.FileSearch.Jump", resourceCulture)!;

    public static string Dialog_FileSearch_Results => ResourceManager.GetString("Dialog.FileSearch.Results", resourceCulture)!;

    public static string Dialog_FileSearch_Count => ResourceManager.GetString("Dialog.FileSearch.Count", resourceCulture)!;

    public static string Dialog_FileSearch_BaseDirectoryNotFound => ResourceManager.GetString("Dialog.FileSearch.BaseDirectoryNotFound", resourceCulture)!;

    public static string Dialog_FileSearch_Searching => ResourceManager.GetString("Dialog.FileSearch.Searching", resourceCulture)!;

    public static string Dialog_FileSearch_Progress => ResourceManager.GetString("Dialog.FileSearch.Progress", resourceCulture)!;

    public static string Dialog_Progress_Copying => ResourceManager.GetString("Dialog.Progress.Copying", resourceCulture)!;

    public static string Dialog_Progress_Duplicating => ResourceManager.GetString("Dialog.Progress.Duplicating", resourceCulture)!;

    public static string Dialog_Progress_Moving => ResourceManager.GetString("Dialog.Progress.Moving", resourceCulture)!;

    public static string Dialog_Progress_Count => ResourceManager.GetString("Dialog.Progress.Count", resourceCulture)!;

    public static string Dialog_Progress_CountUnknown => ResourceManager.GetString("Dialog.Progress.CountUnknown", resourceCulture)!;

    public static string Dialog_Progress_Canceling => ResourceManager.GetString("Dialog.Progress.Canceling", resourceCulture)!;

    public static string Dialog_Progress_Canceled => ResourceManager.GetString("Dialog.Progress.Canceled", resourceCulture)!;

    public static string Dialog_Bookmark_CurrentPath => ResourceManager.GetString("Dialog.Bookmark.CurrentPath", resourceCulture)!;

    public static string Dialog_Bookmark_Add => ResourceManager.GetString("Dialog.Bookmark.Add", resourceCulture)!;

    public static string Dialog_Bookmark_Edit => ResourceManager.GetString("Dialog.Bookmark.Edit", resourceCulture)!;

    public static string Dialog_Bookmark_Path => ResourceManager.GetString("Dialog.Bookmark.Path", resourceCulture)!;

    public static string Dialog_Bookmark_Delete => ResourceManager.GetString("Dialog.Bookmark.Delete", resourceCulture)!;

    public static string Dialog_Bookmark_Jump => ResourceManager.GetString("Dialog.Bookmark.Jump", resourceCulture)!;

    public static string Status_PropertiesUnavailable => ResourceManager.GetString("Status.PropertiesUnavailable", resourceCulture)!;

    public static string Dialog_Diff_Title => ResourceManager.GetString("Dialog.Diff.Title", resourceCulture)!;

    public static string Dialog_Diff_DifferencesOnly => ResourceManager.GetString("Dialog.Diff.DifferencesOnly", resourceCulture)!;

    public static string ContextMenu_Open => ResourceManager.GetString("ContextMenu.Open", resourceCulture)!;

    public static string ContextMenu_Edit => ResourceManager.GetString("ContextMenu.Edit", resourceCulture)!;

    public static string ContextMenu_Copy => ResourceManager.GetString("ContextMenu.Copy", resourceCulture)!;

    public static string ContextMenu_Move => ResourceManager.GetString("ContextMenu.Move", resourceCulture)!;

    public static string ContextMenu_Rename => ResourceManager.GetString("ContextMenu.Rename", resourceCulture)!;

    public static string ContextMenu_Duplicate => ResourceManager.GetString("ContextMenu.Duplicate", resourceCulture)!;

    public static string ContextMenu_Delete => ResourceManager.GetString("ContextMenu.Delete", resourceCulture)!;

    public static string ContextMenu_CopyPath => ResourceManager.GetString("ContextMenu.CopyPath", resourceCulture)!;

    public static string ContextMenu_RevealInFinder => ResourceManager.GetString("ContextMenu.RevealInFinder", resourceCulture)!;

    public static string ContextMenu_Properties => ResourceManager.GetString("ContextMenu.Properties", resourceCulture)!;

    public static string ContextMenu_NewFolder => ResourceManager.GetString("ContextMenu.NewFolder", resourceCulture)!;

    public static string ContextMenu_NewFile => ResourceManager.GetString("ContextMenu.NewFile", resourceCulture)!;

    public static string ContextMenu_OpenInTerminal => ResourceManager.GetString("ContextMenu.OpenInTerminal", resourceCulture)!;

    public static string ContextMenu_Refresh => ResourceManager.GetString("ContextMenu.Refresh", resourceCulture)!;

    public static string ContextMenu_Settings => ResourceManager.GetString("ContextMenu.Settings", resourceCulture)!;

    public static string Dialog_Settings_Title => ResourceManager.GetString("Dialog.Settings.Title", resourceCulture)!;

    public static string Dialog_Settings_SearchPlaceholder => ResourceManager.GetString("Dialog.Settings.SearchPlaceholder", resourceCulture)!;

    public static string Dialog_Settings_Section_General => ResourceManager.GetString("Dialog.Settings.Section.General", resourceCulture)!;

    public static string Dialog_Settings_Section_External => ResourceManager.GetString("Dialog.Settings.Section.External", resourceCulture)!;

    public static string Dialog_Settings_Section_Bookmarks => ResourceManager.GetString("Dialog.Settings.Section.Bookmarks", resourceCulture)!;

    public static string Dialog_Settings_Section_Keymap => ResourceManager.GetString("Dialog.Settings.Section.Keymap", resourceCulture)!;

    public static string Dialog_Settings_Theme => ResourceManager.GetString("Dialog.Settings.Theme", resourceCulture)!;

    public static string Dialog_Settings_Theme_System => ResourceManager.GetString("Dialog.Settings.Theme.System", resourceCulture)!;

    public static string Dialog_Settings_Theme_Light => ResourceManager.GetString("Dialog.Settings.Theme.Light", resourceCulture)!;

    public static string Dialog_Settings_Theme_Dark => ResourceManager.GetString("Dialog.Settings.Theme.Dark", resourceCulture)!;

    public static string Dialog_Settings_Language => ResourceManager.GetString("Dialog.Settings.Language", resourceCulture)!;

    public static string Dialog_Settings_Language_System => ResourceManager.GetString("Dialog.Settings.Language.System", resourceCulture)!;

    public static string Dialog_Settings_Language_English => ResourceManager.GetString("Dialog.Settings.Language.English", resourceCulture)!;

    public static string Dialog_Settings_Language_Japanese => ResourceManager.GetString("Dialog.Settings.Language.Japanese", resourceCulture)!;

    public static string Dialog_Settings_RestartHint => ResourceManager.GetString("Dialog.Settings.RestartHint", resourceCulture)!;

    public static string Dialog_Settings_ExternalEditor => ResourceManager.GetString("Dialog.Settings.ExternalEditor", resourceCulture)!;

    public static string Dialog_Settings_OpenKeymap => ResourceManager.GetString("Dialog.Settings.OpenKeymap", resourceCulture)!;

    public static string Dialog_Settings_NoMatches => ResourceManager.GetString("Dialog.Settings.NoMatches", resourceCulture)!;

    public static string Dialog_Keymap_Title => ResourceManager.GetString("Dialog.Keymap.Title", resourceCulture)!;

    public static string Dialog_Keymap_Column_Command => ResourceManager.GetString("Dialog.Keymap.Column.Command", resourceCulture)!;

    public static string Dialog_Keymap_Column_Key => ResourceManager.GetString("Dialog.Keymap.Column.Key", resourceCulture)!;

    public static string Dialog_Keymap_Edit => ResourceManager.GetString("Dialog.Keymap.Edit", resourceCulture)!;

    public static string Dialog_Keymap_Reset => ResourceManager.GetString("Dialog.Keymap.Reset", resourceCulture)!;

    public static string Dialog_Keymap_Capture_Title => ResourceManager.GetString("Dialog.Keymap.Capture.Title", resourceCulture)!;

    public static string Dialog_Keymap_Capture_Prompt => ResourceManager.GetString("Dialog.Keymap.Capture.Prompt", resourceCulture)!;

    public static string Dialog_Sort_Title => ResourceManager.GetString("Dialog.Sort.Title", resourceCulture)!;

    public static string Dialog_Sort_Method => ResourceManager.GetString("Dialog.Sort.Method", resourceCulture)!;

    public static string Dialog_Sort_Order => ResourceManager.GetString("Dialog.Sort.Order", resourceCulture)!;

    public static string Dialog_Sort_Name => ResourceManager.GetString("Dialog.Sort.Name", resourceCulture)!;

    public static string Dialog_Sort_Extension => ResourceManager.GetString("Dialog.Sort.Extension", resourceCulture)!;

    public static string Dialog_Sort_Date => ResourceManager.GetString("Dialog.Sort.Date", resourceCulture)!;

    public static string Dialog_Sort_Size => ResourceManager.GetString("Dialog.Sort.Size", resourceCulture)!;

    public static string Dialog_Sort_Attributes => ResourceManager.GetString("Dialog.Sort.Attributes", resourceCulture)!;

    public static string Dialog_Sort_None => ResourceManager.GetString("Dialog.Sort.None", resourceCulture)!;

    public static string Dialog_Sort_Ascending => ResourceManager.GetString("Dialog.Sort.Ascending", resourceCulture)!;

    public static string Dialog_Sort_Descending => ResourceManager.GetString("Dialog.Sort.Descending", resourceCulture)!;

    public static string Dialog_Delete_Title => ResourceManager.GetString("Dialog.Delete.Title", resourceCulture)!;

    public static string Dialog_Delete_MessageSingle => ResourceManager.GetString("Dialog.Delete.MessageSingle", resourceCulture)!;

    public static string Dialog_Delete_MessageMultiple => ResourceManager.GetString("Dialog.Delete.MessageMultiple", resourceCulture)!;

    public static string Dialog_ReadOnlyDelete_Title => ResourceManager.GetString("Dialog.ReadOnlyDelete.Title", resourceCulture)!;

    public static string Dialog_ReadOnlyDelete_Message => ResourceManager.GetString("Dialog.ReadOnlyDelete.Message", resourceCulture)!;

    public static string Dialog_ReadOnlyDelete_Delete => ResourceManager.GetString("Dialog.ReadOnlyDelete.Delete", resourceCulture)!;

    public static string Dialog_Conflict_Title => ResourceManager.GetString("Dialog.Conflict.Title", resourceCulture)!;

    public static string Dialog_Conflict_Message => ResourceManager.GetString("Dialog.Conflict.Message", resourceCulture)!;

    public static string Dialog_Conflict_ApplyToAll => ResourceManager.GetString("Dialog.Conflict.ApplyToAll", resourceCulture)!;

    public static string Dialog_Conflict_Overwrite => ResourceManager.GetString("Dialog.Conflict.Overwrite", resourceCulture)!;

    public static string Dialog_Conflict_Skip => ResourceManager.GetString("Dialog.Conflict.Skip", resourceCulture)!;
}
