//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsFiler.Presentation.Resources;

using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("PublicResXFileCodeGenerator", "")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Strings
{
    private static ResourceManager resourceMan;

    private static CultureInfo resourceCulture;

    public Strings()
    {
    }

    public static ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                resourceMan = new ResourceManager("WsFiler.Presentation.Resources.Strings", typeof(Strings).Assembly);
            }

            return resourceMan;
        }
    }

    public static CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string App_Title => ResourceManager.GetString("App.Title", resourceCulture)!;

    public static string Menu_AboutWsFiler => ResourceManager.GetString("Menu.AboutWsFiler", resourceCulture)!;

    public static string About_Title => ResourceManager.GetString("About.Title", resourceCulture)!;

    public static string About_Description => ResourceManager.GetString("About.Description", resourceCulture)!;

    public static string Status_Ready => ResourceManager.GetString("Status.Ready", resourceCulture)!;

    public static string Status_PreviewUnavailable => ResourceManager.GetString("Status.PreviewUnavailable", resourceCulture)!;

    public static string Status_NoItemToCopy => ResourceManager.GetString("Status.NoItemToCopy", resourceCulture)!;

    public static string Status_NoItemToMove => ResourceManager.GetString("Status.NoItemToMove", resourceCulture)!;

    public static string Status_NoItemToDelete => ResourceManager.GetString("Status.NoItemToDelete", resourceCulture)!;

    public static string Status_NoItemToRename => ResourceManager.GetString("Status.NoItemToRename", resourceCulture)!;

    public static string Status_Copied => ResourceManager.GetString("Status.Copied", resourceCulture)!;

    public static string Status_Moved => ResourceManager.GetString("Status.Moved", resourceCulture)!;

    public static string Status_Deleted => ResourceManager.GetString("Status.Deleted", resourceCulture)!;

    public static string Status_Renamed => ResourceManager.GetString("Status.Renamed", resourceCulture)!;

    public static string Status_AlreadyAtRoot => ResourceManager.GetString("Status.AlreadyAtRoot", resourceCulture)!;

    public static string Dialog_Copy_Title => ResourceManager.GetString("Dialog.Copy.Title", resourceCulture)!;

    public static string Dialog_Copy_MessageSingle => ResourceManager.GetString("Dialog.Copy.MessageSingle", resourceCulture)!;

    public static string Dialog_Copy_MessageMultiple => ResourceManager.GetString("Dialog.Copy.MessageMultiple", resourceCulture)!;

    public static string Dialog_Copy_Destination => ResourceManager.GetString("Dialog.Copy.Destination", resourceCulture)!;

    public static string Dialog_Move_Title => ResourceManager.GetString("Dialog.Move.Title", resourceCulture)!;

    public static string Dialog_Move_MessageSingle => ResourceManager.GetString("Dialog.Move.MessageSingle", resourceCulture)!;

    public static string Dialog_Move_MessageMultiple => ResourceManager.GetString("Dialog.Move.MessageMultiple", resourceCulture)!;

    public static string Dialog_Move_Destination => ResourceManager.GetString("Dialog.Move.Destination", resourceCulture)!;

    public static string Dialog_Rename_Title => ResourceManager.GetString("Dialog.Rename.Title", resourceCulture)!;

    public static string Dialog_Rename_NewName => ResourceManager.GetString("Dialog.Rename.NewName", resourceCulture)!;

    public static string Dialog_Common_Ok => ResourceManager.GetString("Dialog.Common.Ok", resourceCulture)!;

    public static string Dialog_Common_Yes => ResourceManager.GetString("Dialog.Common.Yes", resourceCulture)!;

    public static string Dialog_Common_No => ResourceManager.GetString("Dialog.Common.No", resourceCulture)!;

    public static string Dialog_Common_Cancel => ResourceManager.GetString("Dialog.Common.Cancel", resourceCulture)!;

    public static string Dialog_Preview_Title => ResourceManager.GetString("Dialog.Preview.Title", resourceCulture)!;

    public static string Dialog_Preview_Truncated => ResourceManager.GetString("Dialog.Preview.Truncated", resourceCulture)!;

    public static string Grid_Column_Name => ResourceManager.GetString("Grid.Column.Name", resourceCulture)!;

    public static string Grid_Column_Ext => ResourceManager.GetString("Grid.Column.Ext", resourceCulture)!;

    public static string Grid_Column_Size => ResourceManager.GetString("Grid.Column.Size", resourceCulture)!;

    public static string Grid_Column_Modified => ResourceManager.GetString("Grid.Column.Modified", resourceCulture)!;

    public static string Pane_Summary => ResourceManager.GetString("Pane.Summary", resourceCulture)!;

    public static string Status_SortChanged => ResourceManager.GetString("Status.SortChanged", resourceCulture)!;

    public static string Status_DirectoryCreated => ResourceManager.GetString("Status.DirectoryCreated", resourceCulture)!;

    public static string Status_FileCreated => ResourceManager.GetString("Status.FileCreated", resourceCulture)!;

    public static string Status_Duplicated => ResourceManager.GetString("Status.Duplicated", resourceCulture)!;

    public static string Status_AttributesChanged => ResourceManager.GetString("Status.AttributesChanged", resourceCulture)!;

    public static string Dialog_Drive_Title => ResourceManager.GetString("Dialog.Drive.Title", resourceCulture)!;

    public static string Dialog_Attributes_Title => ResourceManager.GetString("Dialog.Attributes.Title", resourceCulture)!;

    public static string Dialog_Attributes_ReadOnly => ResourceManager.GetString("Dialog.Attributes.ReadOnly", resourceCulture)!;

    public static string Dialog_Attributes_Hidden => ResourceManager.GetString("Dialog.Attributes.Hidden", resourceCulture)!;

    public static string Dialog_Attributes_Archive => ResourceManager.GetString("Dialog.Attributes.Archive", resourceCulture)!;

    public static string Dialog_Attributes_System => ResourceManager.GetString("Dialog.Attributes.System", resourceCulture)!;

    public static string Dialog_DirectoryCreate_Title => ResourceManager.GetString("Dialog.DirectoryCreate.Title", resourceCulture)!;

    public static string Dialog_DirectoryCreate_Prompt => ResourceManager.GetString("Dialog.DirectoryCreate.Prompt", resourceCulture)!;

    public static string Dialog_FileCreate_Title => ResourceManager.GetString("Dialog.FileCreate.Title", resourceCulture)!;

    public static string Dialog_FileCreate_Prompt => ResourceManager.GetString("Dialog.FileCreate.Prompt", resourceCulture)!;

    public static string Dialog_Filter_Title => ResourceManager.GetString("Dialog.Filter.Title", resourceCulture)!;

    public static string Dialog_Filter_Prompt => ResourceManager.GetString("Dialog.Filter.Prompt", resourceCulture)!;

    public static string Dialog_Editor_Title => ResourceManager.GetString("Dialog.Editor.Title", resourceCulture)!;

    public static string Dialog_Editor_Prompt => ResourceManager.GetString("Dialog.Editor.Prompt", resourceCulture)!;
}
